var xpozycja = 0;
var xprzemieszczenie = 0;
var ypozycja = 0;
var yprzemieszczenie = 0;
var maxSpeed = 20; //PóŸniej bêdzie uzale¿nione od poziomu szybkoœci postaci
var minx = 0;
var miny = 0;
var maxx = 1218;
var maxy = 664;
